version: '3.9'

services:
  bot:
    build: .
    container_name: nestjs-telegram-bot
    ports:
      - "3000:3000"
    environment:
      - DATABASE_URL=file:/app/data/db.sqlite 
    volumes:
      - ./data:/app/data
    restart: always
